#!/bash/bin
if command
then 
   command
else
   command
fi
================================
for [变量] in [列表元素1]  [列表元素2]   [列表元素3]
do
  command
done
//无线循环模式:for (( ; ; ))
================================
while condition
do
command
done

================================
until condition
do 
 command
done
================================
function [函数名](){

return [0-255];默认返回最后一条命令执行的返回值,成功为0,其他为失败.
}
=========文件包含=======================
.空格[文件名]
source [文件名]

================================    
  